source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MapLibraryWrapper_Example', :exclusive => true do
  pod 'MapLibraryWrapper', :path => '../'
  pod 'GoogleMaps'
end

target 'MapLibraryWrapper_Tests', :exclusive => true do
  pod 'MapLibraryWrapper', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
